language: php

php:
  - 7.3

branches:
  only:
    - master
    - development
    - /^issue\/.+$/

before_script:
 - composer self-update
 - mkdir -p vendor/bin
 - mkdir -p build/logs
 - composer install -o --prefer-dist --no-interaction
 - nohup php -S 127.0.0.1:8080 > build/logs/webserver.log 2>&1 &

script:
 - php vendor/bin/spg.phar check:links -g -b "http://127.0.0.1:8080/docs" ./Project.json
